### ISSUE TITLE
New Email Requests do not get purged

### ISSUE THREAD

**Issue by chris68** [TankAuth/Tank-Auth#29]
When a user requests a new email and never answers the respective email then the user remains in that state forever. This might be acceptable for the very user, but one can effectively block another person (the one having this new mail)  from using your application since this person will be told that "his" email is already used. 

Therefore, such requests need to be purged like for users not having activated their account.  An implementation would require the introduction of a timestamp field (similar to created) recording when the users has actually requested the new email.

**Comment by chris68** [comment]
Issue closed since no reaction after over 4 years.

**Comment by enchance** [comment]
Looks like it. I miss this project.
